dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=instagram setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: pZnSNJKM7UDpBvto+PVilu256IjZZX4PDoy+tpyoqzvArLeva+G4b54smP2ZnelxO6WSP2RpPaLJf6kWFOM0zF9Rwznxm31BeAg7mhTRd7TGEo5yiiMf/AlADN4ZwkeeJ3ptR/gorvQnpOaz8IYXqVaBW/02P08QHiKfFGSyQ5w=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
